name: Staff App CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test Staff App
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Staff App Code
        uses: actions/checkout@v3

      # Set up JDK 11 (to match your project's Java version)
      - name: Set up JDK for Staff App
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # Use 'zulu' or 'adopt' as per your preference
          java-version: '11'   # Matches the Java version specified in your Gradle file

      # Cache Gradle dependencies to speed up builds
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set up Android SDK
      - name: Set up Android SDK for Staff App
        uses: android-actions/setup-android@v2
        with:
          api-level: 35                      # Matches your compileSdk and targetSdk
          build-tools: 35.0.0                # Ensure this matches the SDK version used
          ndk: 24.0.8215888

      # Build the app
      - name: Build Staff App with Gradle
        run: ./gradlew build

      # Run unit tests
      - name: Run Unit Tests for Staff App
        run: ./gradlew test

      # Run Android instrumentation tests
      - name: Run Instrumentation Tests for Staff App
        run: ./gradlew connectedAndroidTest

      # Run lint checks
      - name: Run Lint Checks for Staff App
        run: ./gradlew lint