name: Android CI

on:
  push:
    branches: [master]
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install SDK API Level 35
      run: |
        yes | sdkmanager "platforms;android-35" "build-tools;35.0.0"

    - name: Make Gradle Wrapper executable
      run: chmod +x ./gradlew

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk

  deploy:
    needs: build
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
    - name: Download debug APK artifact
      uses: actions/download-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/

    - name: Deploy to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.STAFF_APP_FIREBASE_APP_ID }}
        token: ${{ secrets.FIREBASE_TOKEN }}
#        serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        file: app/build/outputs/apk/debug/app-debug.apk
        # Optionally add testers, groups, releaseNotes
        # testers: "your-email@example.com"
        # groups: "qa"
        # releaseNotes: "Automated build from master branch"