name: Android CI/CD with Version Management

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          yes | sdkmanager "platforms;android-35"
          yes | sdkmanager "build-tools;35.0.0"
          yes | sdkmanager "cmdline-tools;latest"

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

  deploy:
    needs: build
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Increment versionCode and versionName
        run: |
          VERSION_CODE=$(grep versionCode app/build.gradle | awk '{print $2}')
          VERSION_NAME=$(grep versionName app/build.gradle | awk -F '"' '{print $2}')
          NEW_VERSION_CODE=$((VERSION_CODE + 1))
          NEW_VERSION_NAME="${VERSION_NAME%.*}.$((VERSION_CODE + 1))"
          sed -i "s/versionCode $VERSION_CODE/versionCode $NEW_VERSION_CODE/" app/build.gradle
          sed -i "s/versionName \"$VERSION_NAME\"/versionName \"$NEW_VERSION_NAME\"/" app/build.gradle
        shell: bash

      - name: Commit and Push Version Update
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b version-bump || git checkout version-bump
          git reset --hard
          git fetch origin version-bump
          git rebase origin/version-bump
          git add app/build.gradle
          git commit -m "CI: Bump version to $NEW_VERSION_NAME ($NEW_VERSION_CODE)" || echo "No changes to commit"
          git push origin version-bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: version-bump
          title: "CI: Bump version to $NEW_VERSION_NAME ($NEW_VERSION_CODE)"
          body: |
            This pull request updates the version to:
            - **Version Code**: $NEW_VERSION_CODE
            - **Version Name**: $NEW_VERSION_NAME
          labels: version-bump

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_AUTH_TOKEN }}
          file: app/build/outputs/apk/debug/app-debug.apk
          groups: "vexa.testers.com"